import Footer from "@/components/Footer"
import Navbar from "@/components/Navbar"
import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import { Bricolage_Grotesque, Inter } from "next/font/google"
import "../styles/globals.scss"

const inter = Inter({ subsets: ["latin"] })

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage-grotesque"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, bricolage.variable, "")}>
        <Navbar />

        <main className="pt-28 pb-24 min-h-screen">{children}</main>

        <Footer />
      </body>
    </html>
  )
}
